kind: Pod
apiVersion: v1
metadata:
  name: myenvsecret
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-akshay; sleep 5; done" ]


      env:
        - name: MYENVUSER
          valueFrom:
            secretKeyRef:
                name: mytestsecret
                key: username.txt


        - name: MYENVUSER1
          valueFrom:
            secretKeyRef:
                name: mytestsecret
                key: password.txt


