kind: Pod
apiVersion: v1
metadata:
 name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-akshay; sleep 5; done" ]

  nodeSelector:
    myname: sai      #we used label in the node selector 
