kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
    - name: resource
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-akki; sleep 5; done"]

      resources:
        requests:
          cpu: "64m"
          memory: "100Mi"

        limits:
          cpu: "128m"
          memory: "200Mi"
